apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app2
  template:
    metadata:
      labels:
        app: my-web-app2
    spec:
      containers:
      - name: my-web-app2
        image: tutu1008/my-web-nginx2:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-web-app2-service
spec:
  type: ClusterIP  
  selector:
    app: my-web-app2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
